[zh]
  title = "个人博客"
  languageName = "中文"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/zh"

[en]
  title = "Hugo Zzo Theme"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[ko]
  title = "Hugo Zzo Theme"
  languageName = "한국어"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/ko"
